### PR TITLE
Remove OCSP/CRL hosts

### PR DESCRIPTION
**Pull request by jsf9k**
@konklone recently started publishing [an OCSP/CRL exclusion list](https://github.com/GSA/data/blob/master/dotgov-websites/ocsp-crl.csv).  These changes pull down that list and use it to remove matching hosts from the list to be scanned.

We exclude OCSP/CRL hosts from scanning because [they do not fall under the scope of the BOD](https://https.cio.gov/guide/#are-federally-operated-certificate-revocation-services-crl-ocsp-also-required-to-move-to-https).

### CODE REVIEW

**Comment by h-m-f-t** [comment]
I agree these hosts are out-of-scope -- but it would be nice if they were still represented in the HTTPS Report as OCSP/CRL hosts.

**Review by dav3r — APPROVED** [review]
This change looks good, but I agree with @h-m-f-t that it would be nice to list the skipped OCSP/CRL hosts somewhere in the HTTPS report.

**Comment by jsf9k** [comment]
@h-m-f-t and @dav3r, would you be happy if we added an attachment containing all the skipped OCSP/CRL hosts and added a blurb to the report explaining that?

**Comment by dav3r** [comment]
@jsf9k that sounds like a reasonable and relatively easy way to accomplish this.  It would be nice to have the attachment only include the skipped OCSP/CRL hosts owned by the organization receiving the HTTPS report (and not include the attachment at all if there were no OSCP/CRL hosts for that org) , but I understand that is more work.  I think your solution is a fine starting point.

**Comment by jsf9k** [comment]
@dav3r and @h-m-f-t (and anyone else who wants to respond):

- Are we fine with including the whole OCSP/CRL CSV attachment in the HTTPS report for now?  I think @dav3r said he was OK with that, but I want to make sure we're all on board.  It's a little complicated to create that OCSP/CRL exclusion CSV separately for each agency, so my thought was that we should get it out there, get agencies to start contributing their OCSP/CRL hosts to [the exclusion list](https://github.com/GSA/data/blob/master/dotgov-websites/ocsp-crl.csv), and make agency-specific lists in a future pull request.
- Since we currently use the same CSV of hosts to scan for the HTTPS and Trustworthy Email scans, the OCSP/CRL hosts will also excluded from the Trustworthy Email scans.  Is this OK, or should I make different CSVs for the two scans?  I'm leaning toward the latter, since folks still wouldn't want evil-doers sending emails from their OCSP/CRL domains, but I wanted your input.

**Comment by dav3r** [comment]
@jsf9k I agree with you that we should have a different CSV for Trustymail for the reason you mentioned.

**Comment by h-m-f-t** [comment]
I think the more we can do the hard work to make it easy for users to user our info, the better for everyone. If I had my druthers, I'd love for the HTTPS Report to indicate *in line* that a host is an OCSP/CRL host and for pshtt results to indicate that a host was OCSP/CRL according to a checked exception file. But adding a holistic OCSP/CRL CSV as a temporary step to alleviate the compliance pain agencies feel  seems ok to me. 

Presuming a complete exclusion list, I think it'd be comprehensive for all agencies' digital services. I think a single list would be ok, and don't see the need to separate them for web v. email.

> ...make agency-specific lists in a future pull request

I feel like I'm missing something. If the OCSP/CRL host is on something.gov and we know something.gov is owned by e.g., the Department of Administrative Affairs, is making it so that the OCSP/CRL attachment that hits agencies consists solely of their hosts a challenge?

**Comment by jsf9k** [comment]
@h-m-f-t 

>  Presuming a complete exclusion list...

The question wasn't whether to generate separate exclusion lists, but whether OCSP/CRL hosts should be exempt from Trustworthy Email scanning.  @dav3r and I were thinking not, since even though such sites need not use HTTPS one would want them under a DMARC policy.  Do you feel otherwise?

> I feel like I'm missing something...

It's not a challenge, but it will require writing some code.  I'll try to get to it this weekend.

**Comment by h-m-f-t** [comment]
@jsf9k ah I understand now. No, I don't think these hostnames should be exempt from Trustworthy Email scanning.

>It's not a challenge, but it will require writing some code. I'll try to get to it this weekend.

You're a wizard, Harry! 🇺🇸

**Comment by jsf9k** [comment]
The exclusion of OCSP domains will be handled at the reporting stage.

**Pull request closed without merging**
